---

- name: Directory /etc/network/firewall
  become: yes
  file: path=/etc/network/firewall state=directory owner=root group=root mode=0755

- name: Load Firewall before Network Up
  become: yes
  copy: src=firewall-reload dest=/etc/network/if-pre-up.d/firewall-reload owner=root group=root mode=0755
  notify: Firewall Reload

- name: Firewall IPTables Rules
  template: src=iptables.config.j2 dest=/etc/network/firewall/iptables.config owner=root group=root mode=0644
  become: yes
  notify: Firewall Reload

# Reload Firewall
# Changes may not be able to wait
- meta: flush_handlers
